# Generated by Django 3.0.8 on 2020-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.AddField(
            model_name='course',
            name='brief_desc',
            field=models.CharField(default='individual', max_length=15000),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='individual', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default='', upload_to='rm/images'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_desc',
            field=models.CharField(default='individual', max_length=5000),
        ),
    ]
