# Generated by Django 3.0.8 on 2020-10-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0003_auto_20201004_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_desc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
