# Generated by Django 3.0.8 on 2020-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0004_course_show_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='display_img',
            field=models.ImageField(default='', upload_to='rm/images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='show_desc',
            field=models.CharField(default='', max_length=70),
        ),
    ]
