# Generated by Django 3.0.8 on 2020-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0006_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brief_desc',
            field=models.TextField(default='', max_length=15000),
        ),
    ]
