# Generated by Django 3.0.8 on 2020-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0007_auto_20201005_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='brief_desc',
            field=models.FileField(default='', max_length=15000, upload_to=''),
        ),
    ]
