# Generated by Django 3.0.8 on 2020-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0009_auto_20201005_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='files',
            field=models.FileField(default='file comming soon', upload_to='rm/files'),
            preserve_default=False,
        ),
    ]
