# Generated by Django 3.0.8 on 2020-10-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0011_auto_20201007_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='files',
        ),
        migrations.RemoveField(
            model_name='course',
            name='show_desc',
        ),
    ]
